In [7]:
import sqlite3
import pandas as pd

In [8]:
conn = sqlite3.connect('emp.db')
c = conn.cursor()

c.execute('DROP TABLE IF EXISTS EMP')
c.execute('''CREATE TABLE EMP
(
   EMPNO INT PRIMARY KEY NOT NULL,
   ENAME CHAR(50) NOT NULL,
   JOB   CHAR(50) NOT NULL,
   MGR   INT,
   HIREDATE DATE,
   SAL   DECIMAL(10, 2),
   COMM  DECIMAL(10, 2),
   DEPTNO INT
);
''')

In [9]:
emp_df = pd.read_csv('emp.csv')
emp_df.to_sql('EMP', conn, if_exists='append', index=False)

c.execute('SELECT * FROM emp')
print(c.fetchall())

[(7369, 'SMITH', 'CLERK', 7902, '17-Dec-05', 800, None, 20), (7499, 'ALLEN', 'SALESMAN', 7698, '20-Feb-06', 1600, 300, 30), (7521, 'WARD', 'SALESMAN', 7698, '22-Feb-06', 1250, 500, 30), (7566, 'JONES', 'MANAGER', 7839, '2-Apr-06', 2975, None, 20), (7654, 'MARTIN', 'SALESMAN', 7698, '28-Sep-06', 1250, 1400, 30), (7698, 'BLAKE', 'MANAGER', 7839, '1-May-06', 2850, None, 30), (7782, 'CLARK', 'MANAGER', 7839, '9-Jun-06', 2450, None, 10), (7788, 'SCOTT', 'ANALYST', 7566, '9-Dec-07', 3000, None, 20), (7839, 'KING', 'PRESIDENT', None, '17-Nov-06', 5000, None, 10), (7844, 'TURNER', 'SALESMAN', 7698, '8-Sep-06', 1500, 0, 30), (7876, 'ADAMS', 'CLERK', 7788, '12-Jan-08', 1100, None, 20), (7900, 'JAMES', 'CLERK', 7698, '3-Dec-06', 950, None, 30), (7902, 'FORD', 'ANALYST', 7566, '3-Dec-06', 3000, None, 20), (7934, 'MILLER', 'CLERK', 7782, '23-Jan-07', 1300, None, 10)]

In [10]:
c.execute('DROP TABLE emp;')

In [11]:
read_emp = pd.read_csv(r'emp.csv')
read_emp.to_sql('emp', conn, if_exists='append', index = False)

14

In [12]:
c.execute('''CREATE TABLE DEPT(
   DEPTNO INT PRIMARY KEY      NOT NULL,
   DNAME           CHAR(50) NOT NULL,
   LOC         CHAR(50)      NOT NULL
);''')

In [13]:
import csv
dept_file = open("dept.csv")
dept_rows = csv.reader(dept_file)
c. executemany("INSERT INTO dept VALUES (?, ?, ?)", dept_rows)

In [14]:
#  Returning Query Results in a Specified Order
c.execute(''' select ENAME, JOB, SAL
from emp
where DEPTNO = 10
order by sal desc;

''')

df = pd.DataFrame(c.fetchall(), columns=['ENAME', 'JOB', 'SAL'])
display(df)

    ENAME        JOB   SAL
0    KING  PRESIDENT  5000
1   CLARK    MANAGER  2450
2  MILLER      CLERK  1300

In [15]:
# Returning Query Results in a Specified Order
c.execute(''' select ENAME, JOB, SAL
from emp
where DEPTNO = 10
order by sal asc;

''')

df = pd.DataFrame(c.fetchall(), columns=['ENAME', 'JOB', 'SAL'])
display(df)

    ENAME        JOB   SAL
0  MILLER      CLERK  1300
1   CLARK    MANAGER  2450
2    KING  PRESIDENT  5000

In [16]:
#  Returning Query Results in a Specified Order
c.execute(''' select ENAME, JOB, SAL
from emp
where DEPTNO = 10
order by 3 desc;

''')

df = pd.DataFrame(c.fetchall(), columns=['ENAME', 'JOB', 'SAL'])
display(df)

    ENAME        JOB   SAL
0    KING  PRESIDENT  5000
1   CLARK    MANAGER  2450
2  MILLER      CLERK  1300

In [17]:
# Sorting by Multiple Fields
c.execute(''' select EMPNO, DEPTNO, SAL, ENAME, JOB
from emp
order by DEPTNO, SAL desc;

''')

df = pd.DataFrame(c.fetchall(), columns=['ENAME', 'DEPTNO', 'SAL', 'ENAME', 'JOB'])
display(df)

   ENAME  DEPTNO   SAL   ENAME        JOB
0   7839      10  5000    KING  PRESIDENT
1   7782      10  2450   CLARK    MANAGER
2   7934      10  1300  MILLER      CLERK
3   7788      20  3000   SCOTT    ANALYST
4   7902      20  3000    FORD    ANALYST
5   7566      20  2975   JONES    MANAGER
6   7876      20  1100   ADAMS      CLERK
7   7369      20   800   SMITH      CLERK
8   7698      30  2850   BLAKE    MANAGER
9   7499      30  1600   ALLEN   SALESMAN
10  7844      30  1500  TURNER   SALESMAN
11  7521      30  1250    WARD   SALESMAN
12  7654      30  1250  MARTIN   SALESMAN
13  7900      30   950   JAMES      CLERK

In [18]:
# Sorting by Substrings
c.execute(''' select ENAME, JOB
from emp
order by substr(JOB, length(JOB)-1)

''')

df = pd.DataFrame(c.fetchall(), columns=['ENAME', 'JOB'])
display(df)

     ENAME        JOB
0    ALLEN   SALESMAN
1     WARD   SALESMAN
2   MARTIN   SALESMAN
3   TURNER   SALESMAN
4    JONES    MANAGER
5    BLAKE    MANAGER
6    CLARK    MANAGER
7     KING  PRESIDENT
8    SMITH      CLERK
9    ADAMS      CLERK
10   JAMES      CLERK
11  MILLER      CLERK
12   SCOTT    ANALYST
13    FORD    ANALYST

In [21]:
# View
c.execute(''' create view V1
as
select ENAME||' '||DEPTNO as data
from emp;

''')

c.execute('''select * from V2''')

df = pd.DataFrame(c.fetchall(), columns=['DATA'])
display(df)

         DATA
0    SMITH 20
1    ALLEN 30
2     WARD 30
3    JONES 20
4   MARTIN 30
5    BLAKE 30
6    CLARK 10
7    SCOTT 20
8     KING 10
9   TURNER 30
10   ADAMS 20
11   JAMES 30
12    FORD 20
13  MILLER 10

In [22]:
# Null String handling
c.execute('''select ENAME, SAL, COMM
from emp
order by 3;
''')

df = pd.DataFrame(c.fetchall(), columns=['ENAME','SAL','COMM'])
display(df)

     ENAME   SAL    COMM
0    SMITH   800     NaN
1    JONES  2975     NaN
2    BLAKE  2850     NaN
3    CLARK  2450     NaN
4    SCOTT  3000     NaN
5     KING  5000     NaN
6    ADAMS  1100     NaN
7    JAMES   950     NaN
8     FORD  3000     NaN
9   MILLER  1300     NaN
10  TURNER  1500     0.0
11   ALLEN  1600   300.0
12    WARD  1250   500.0
13  MARTIN  1250  1400.0

In [23]:
# case expression for Null handling
c.execute('''select ENAME, SAL, COMM
from (select ENAME,SAL,COMM,case when COMM is null then 0 else 1 end as is_null
from emp) x
order by is_null desc,COMM
''')

df = pd.DataFrame(c.fetchall(), columns=['ENAME','SAL','COMM'])
display(df)

     ENAME   SAL    COMM
0   TURNER  1500     0.0
1    ALLEN  1600   300.0
2     WARD  1250   500.0
3   MARTIN  1250  1400.0
4    SMITH   800     NaN
5    JONES  2975     NaN
6    BLAKE  2850     NaN
7    CLARK  2450     NaN
8    SCOTT  3000     NaN
9     KING  5000     NaN
10   ADAMS  1100     NaN
11   JAMES   950     NaN
12    FORD  3000     NaN
13  MILLER  1300     NaN

In [24]:
# Null at end
c.execute('''select ENAME, SAL, COMM
from (select ENAME,SAL,COMM,case when COMM is null then 0 else 1 end as is_null
from emp) x
order by is_null desc,COMM desc
''')

df = pd.DataFrame(c.fetchall(), columns=['ENAME','SAL','COMM'])
display(df)

     ENAME   SAL    COMM
0   MARTIN  1250  1400.0
1     WARD  1250   500.0
2    ALLEN  1600   300.0
3   TURNER  1500     0.0
4    SMITH   800     NaN
5    JONES  2975     NaN
6    BLAKE  2850     NaN
7    CLARK  2450     NaN
8    SCOTT  3000     NaN
9     KING  5000     NaN
10   ADAMS  1100     NaN
11   JAMES   950     NaN
12    FORD  3000     NaN
13  MILLER  1300     NaN

In [30]:
# Null at start with sal desc
c.execute('''select ename,sal,comm
from emp
order by comm desc nulls first''')

df = pd.DataFrame(c.fetchall(), columns=['ENAME','SAL','COMM'])
display(df)

     ENAME   SAL    COMM
0    SMITH   800     NaN
1    JONES  2975     NaN
2    BLAKE  2850     NaN
3    CLARK  2450     NaN
4    SCOTT  3000     NaN
5     KING  5000     NaN
6    ADAMS  1100     NaN
7    JAMES   950     NaN
8     FORD  3000     NaN
9   MILLER  1300     NaN
10  MARTIN  1250  1400.0
11    WARD  1250   500.0
12   ALLEN  1600   300.0
13  TURNER  1500     0.0

In [31]:
# Sorting
c.execute('''select ENAME, SAL, JOB, COMM,
case when JOB = 'SALESMAN' then COMM else SAL end as ORDERED
from emp
order by 5;

''')

df = pd.DataFrame(c.fetchall(), columns=['ENAME','SAL', 'JOB','COMM', 'ORDERED'])
display(df)

     ENAME   SAL        JOB    COMM  ORDERED
0   TURNER  1500   SALESMAN     0.0      0.0
1    ALLEN  1600   SALESMAN   300.0    300.0
2     WARD  1250   SALESMAN   500.0    500.0
3    SMITH   800      CLERK     NaN    800.0
4    JAMES   950      CLERK     NaN    950.0
5    ADAMS  1100      CLERK     NaN   1100.0
6   MILLER  1300      CLERK     NaN   1300.0
7   MARTIN  1250   SALESMAN  1400.0   1400.0
8    CLARK  2450    MANAGER     NaN   2450.0
9    BLAKE  2850    MANAGER     NaN   2850.0
10   JONES  2975    MANAGER     NaN   2975.0
11   SCOTT  3000    ANALYST     NaN   3000.0
12    FORD  3000    ANALYST     NaN   3000.0
13    KING  5000  PRESIDENT     NaN   5000.0